[package]
authors = ["Pawel Urbanek <contact@pawelurbanek.com>"]
categories = ["database"]
description = "PostgreSQL performance database insights"
edition = "2021"
license = "MIT"
name = "pg-extras"
readme = "README.md"
repository = "https://github.com/pawurb/rust-pg-extras"
version = "0.0.3"

exclude = [
  "docker-compose.yml.sample",
  "live_tests.sh",
]

[dependencies]
pg_interval = "0.4.2"
postgres = "0.19.7"
prettytable-rs = "^0.10"
rust_decimal = {version = "1.32", features = ["db-postgres"]}
rust_decimal_macros = "1.33"
