name: Rust CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run PostgreSQL 14
        run: |
          docker run --env POSTGRES_USER=postgres \
            --env POSTGRES_DB=rust_pg_extras \
            --env POSTGRES_PASSWORD=secret \
            -d -p 5432:5432 postgres:14.6-alpine \
            postgres -c shared_preload_libraries=pg_stat_statements
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Check
        uses: actions-rs/cargo@v1
        with:
          command: check
      - name: Lint
        run: cargo clippy --all --all-features -- -D warnings
      - name: Test
        env:
          DATABASE_URL: postgresql://postgres:secret@localhost:5432/rust_pg_extras
        uses: actions-rs/cargo@v1
        with:
          command: test